project:
  type: website
  output-dir: docs

website:
  title: "ASA Privacy & Confidentiality Interest Group (ASA PCIG)"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - join.qmd
      - about.qmd
      - news.qmd
      - events.qmd
      - resources.qmd
      - contact.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



